### PR TITLE
check controllers for params fixes #1

### LINKED ISSUE #1: support for controllers
Hey, amazingly useful package. I was wondering if it would be trivial to also support setting these properties on iron router controllers for brevity?

### PR DESCRIPTION
**Pull request by chrisbutler**

### CODE REVIEW

**Comment by chrisbutler** [comment]
@dr-dimitru this works for me, though i'm not sure it's entirely right. thoughts?

**Comment by dr-dimitru** [comment]
I'll test, add docs and bump version - later today, thank you for contribution.

**Comment by chrisbutler** [comment]
@dr-dimitru happy to help. i refactored things a bit since my addition made things somewhat messy. 

i've tested and all seems to be working. and specific route settings overwrite controller settings, which is what the user would expect

**Comment by dr-dimitru** [comment]
@chrisbutler could you please add code sample to docs? (sorry I don't have time for it)

**Comment by chrisbutler** [comment]
@dr-dimitru how's this?

**Pull request merged**
